// Package execrecord describes the outcome of running a command, independently of
// how or where it ran.
//
// ExecutionRecord captures what a command produced: its exit code, its output
// streams, and when it started. ExitCode names the exit codes themselves, and holds
// only POSIX process exit statuses (0-255) as reported by a shell, including the
// 128+n signal codes.
//
// A record therefore exists only when a command actually ran. Outcomes that produce
// no exit status are not representable: an executor that never obtained one reports
// that as an error, and a caller that decided an outcome without running anything
// records that as a verdict of its own.
//
// A record deliberately carries no identity for whatever the command ran against —
// no namespace, pod, container, or host. Callers supply that as parameters when they
// execute, so they already hold it, and leaving it out is what lets a Kubernetes
// executor and a local-process executor share one type.
//
// The package has no dependencies beyond the standard library. Helpers that unwrap
// an error from a specific execution backend belong with that backend, not here.
package execrecord

import (
	"fmt"
	"strings"
	"time"
)

// ExecutionRecord encapsulates the outcome of executing a command.
//   - RetCode: the POSIX exit status of the command. Success (0) indicates it ran and
//     exited cleanly.
//   - Error: the error reported by the execution backend, split into lines.
//   - Stdout: the standard output generated by the command, split into lines.
//   - Stderr: the standard error output generated by the command, split into lines.
//   - ExecTime: when execution started.
//
// The three line-oriented fields are nil when the corresponding stream was empty,
// never a single empty string.
type ExecutionRecord struct {
	RetCode  ExitCode  `json:"RetCode"`
	Error    []string  `json:"Error"`
	Stdout   []string  `json:"Stdout"`
	Stderr   []string  `json:"Stderr"`
	ExecTime time.Time `json:"ExecTime"`
}

// New builds an ExecutionRecord from the raw output of a command.
//
// Each stream is split into lines, with trailing blank lines removed. An empty
// stream yields a nil slice rather than a one-element slice holding "", so callers
// can test emptiness with len(). Leading whitespace is preserved: indentation is
// meaningful in command output.
func New(retCode ExitCode, execError string, stdout string, stderr string, execTime time.Time) *ExecutionRecord {
	return &ExecutionRecord{
		RetCode:  retCode,
		Error:    splitLines(strings.TrimSpace(execError)),
		Stdout:   splitLines(strings.TrimRight(stdout, "\r\n\t ")),
		Stderr:   splitLines(strings.TrimRight(stderr, "\r\n\t ")),
		ExecTime: execTime,
	}
}

// splitLines splits an already-trimmed string into lines, returning nil when empty.
func splitLines(s string) []string {
	if len(s) == 0 {
		return nil
	}
	return strings.Split(s, "\n")
}

// String returns a formatted representation of the record, with stdout and stderr
// truncated to keep it usable in a log line. Use Raw for the untruncated form.
func (e *ExecutionRecord) String() string {
	return fmt.Sprintf("RetCode: %d, Error: %s, Stdout: %s, Stderr: %s, ExecTime: %s",
		e.RetCode, strings.Join(e.Error, "\n"), truncate(e.Stdout, 80), truncate(e.Stderr, 80), e.ExecTime)
}

// Raw returns a formatted representation of the record with output streams intact.
func (e *ExecutionRecord) Raw() string {
	return fmt.Sprintf("RetCode: %d, Error: %s, Stdout: %s, Stderr: %s, ExecTime: %s",
		e.RetCode, strings.Join(e.Error, "\n"), strings.Join(e.Stdout, "\n"), strings.Join(e.Stderr, "\n"), e.ExecTime)
}

// truncate joins lines and caps the result at limit bytes, marking any elision.
func truncate(lines []string, limit int) string {
	joined := strings.Join(lines, "\n")
	if len(joined) > limit {
		return joined[:limit] + "..."
	}
	return joined
}
